In [3]:
import pandas as pd


df = pd.read_csv("D:\\datafile\\running_data.csv")
df.head()

    Name  Distance (km)  Time (hours)
0  Wendy           9.10          4.24
1   Yara           8.61          4.16
2  Grace           7.17          2.94
3  Grace           6.36          2.78
4  David           7.96          3.46

In [9]:
df_copy = df.copy()

df_copy["Distance (MI)"] = df_copy["Distance (km)"]/1.609

df_copy.head()

    Name  Distance (km)  Time (hours)  Distance (MI)
0  Wendy           9.10          4.24       5.655687
1   Yara           8.61          4.16       5.351150
2  Grace           7.17          2.94       4.456184
3  Grace           6.36          2.78       3.952766
4  David           7.96          3.46       4.947172

In [10]:
df_copy["Speed per km"] = df_copy["Distance (km)"]/df_copy["Time (hours)"]
df_copy.head()

    Name  Distance (km)  Time (hours)  Distance (MI)  Speed per km
0  Wendy           9.10          4.24       5.655687      2.146226
1   Yara           8.61          4.16       5.351150      2.069712
2  Grace           7.17          2.94       4.456184      2.438776
3  Grace           6.36          2.78       3.952766      2.287770
4  David           7.96          3.46       4.947172      2.300578

In [ ]:
df_copy.merge(df2, left_on="Name", right_on="Runners", how ="left")

In [12]:
df2 = pd.read_csv("D:\\datafile\\runner_rest.csv")
df2.head()

  Runners  Rest Time (Mins)
0   Grace                45
1   Chris                25
2   Frank                58
3   Alice                47
4    Noah               105

In [13]:
df_merge = df_copy.merge(df2, left_on = "Name", right_on = "Runners", how = "inner").drop(columns = "Runners")
df_merge.head()

,Name,Distance (km),Time (hours),Distance (MI),Speed per km,Rest Time (Mins)
0,Wendy,9.10,4.24,5.655687,2.146226,38
1,Grace,7.17,2.94,4.456184,2.438776,45
2,Grace,6.36,2.78,3.952766,2.287770,45
3,Noah,8.95,3.51,5.562461,2.549858,105
4,Wendy,7.74,4.08,4.810441,1.897059,38

In [16]:
df_merge["Rest Time (Hrs)"] = df_merge["Rest Time (Mins)"].apply(lambda x:x/60 if x is not None else None)
df_merge.head()

,Name,Distance (km),Time (hours),Distance (MI),Speed per km,Rest Time (Mins),Rest Time (Hrs)
0,Wendy,9.10,4.24,5.655687,2.146226,38,0.633333
1,Grace,7.17,2.94,4.456184,2.438776,45,0.750000
2,Grace,6.36,2.78,3.952766,2.287770,45,0.750000
3,Noah,8.95,3.51,5.562461,2.549858,105,1.750000
4,Wendy,7.74,4.08,4.810441,1.897059,38,0.633333

In [18]:
over_5_miles_run = df_merge[df_merge["Distance (MI)"].map(lambda x: x) > 5].reset_index(drop = True)
over_5_miles_run.head()

,Name,Distance (km),Time (hours),Distance (MI),Speed per km,Rest Time (Mins),Rest Time (Hrs)
0,Wendy,9.10,4.24,5.655687,2.146226,38,0.633333
1,Noah,8.95,3.51,5.562461,2.549858,105,1.750000
2,Alice,8.41,4.49,5.226849,1.873051,47,0.783333
3,Alice,8.41,4.49,5.226849,1.873051,20,0.333333
4,Bob,10.33,4.95,6.420137,2.086869,60,1.000000

In [24]:
max_distance_index = over_5_miles_run["Distance (MI)"].idxmax()
name = over_5_miles_run["Name"][max_distance_index]
print("the longest distance was achived by",name)

the longest distance was achived by Bob