missing val in each column

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
names = ["carol", "Kate", "Jane", "Kuda", "Tito", "kuku"]
age = [23, np.nan, 34, 56, np.nan, 44]

df = pd.DataFrame({"Names": names, "Age": age})
df

   Names   Age
0  carol  23.0
1   Kate   NaN
2   Jane  34.0
3   Kuda  56.0
4   Tito   NaN
5   kuku  44.0

In [5]:
df.isna().sum()

Names    0
Age      2
dtype: int64

In [6]:
df_copy = df.copy()
df_copy = df_copy.dropna()
df_copy

   Names   Age
0  carol  23.0
2   Jane  34.0
3   Kuda  56.0
5   kuku  44.0

In [7]:
df_copy2 = df.copy()
df_copy2 = df_copy2.fillna(df_copy2["Age"].mean(), inplace = False)

df_copy2

   Names    Age
0  carol  23.00
1   Kate  39.25
2   Jane  34.00
3   Kuda  56.00
4   Tito  39.25
5   kuku  44.00

In [8]:
gender_values = ["F","F","F","M","M","M"]
df_copy2['gender'] = gender_values
df_copy2

   Names    Age gender
0  carol  23.00      F
1   Kate  39.25      F
2   Jane  34.00      F
3   Kuda  56.00      M
4   Tito  39.25      M
5   kuku  44.00      M