In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_excel("D:\\datafile\\Asset_sales_data.xlsx")
df.head()

         date products  sales
0  11-20-2021     cars  19234
1  12-12-2021    boats  87598
2  11-07-2021     cars  15900
3  12-06-2021    boats  12087
4  12-09-2021     cars  56897

In [11]:
print(df.dtypes)

date        object
products    object
sales        int64
dtype: object

In [12]:
df["month"] = pd.to_datetime(df['date']).dt.month
df.head()

         date products  sales  month
0  11-20-2021     cars  19234     11
1  12-12-2021    boats  87598     12
2  11-07-2021     cars  15900     11
3  12-06-2021    boats  12087     12
4  12-09-2021     cars  56897     12

In [15]:
max_sales_month = df.groupby(df['month']).sum(numeric_only = True).idxmax()
max_sales_month

sales    12
dtype: int32