In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
df = pd.read_csv('D:\\datafile\\soccer_strickers.csv')
df.head()

,Player Name,Chances Created,Assists,Goals,Club,Manager,Annual Salary
0,Cristiano Ronaldo,85,20,35,Manchester United,Ole Gunnar Solskjær,"$35,000,000"
1,Lionel Messi,90,25,30,Paris Saint-Germain,Mauricio Pochettino,"$40,000,000"
2,Robert Lewandowski,70,15,40,Bayern Munich,Julian Nagelsmann,"$25,000,000"
3,Erling Haaland,60,10,35,Borussia Dortmund,Marco Rose,"$20,000,000"
4,Kylian Mbappé,80,18,25,Paris Saint-Germain,Mauricio Pochettino,"$30,000,000"

In [27]:
df.isna().sum()

Player Name        0
Chances Created    0
Assists            0
Goals              0
Club               0
Manager            0
Annual Salary      0
dtype: int64

In [28]:
df.dtypes

Player Name        object
Chances Created     int64
Assists             int64
Goals               int64
Club               object
Manager            object
Annual Salary      object
dtype: object

In [29]:
df.duplicated.sum()

AttributeError: 'function' object has no attribute 'sum'

In [30]:
df_copy = df.copy()
df_copy['Annual Salary'] = df_copy['Annual Salary'].str.replace('$', '')
df_copy['Annual Salary'] = df_copy['Annual Salary'].str.replace(',', '').astype(int)

In [31]:
df_copy.head()

,Player Name,Chances Created,Assists,Goals,Club,Manager,Annual Salary
0,Cristiano Ronaldo,85,20,35,Manchester United,Ole Gunnar Solskjær,35000000
1,Lionel Messi,90,25,30,Paris Saint-Germain,Mauricio Pochettino,40000000
2,Robert Lewandowski,70,15,40,Bayern Munich,Julian Nagelsmann,25000000
3,Erling Haaland,60,10,35,Borussia Dortmund,Marco Rose,20000000
4,Kylian Mbappé,80,18,25,Paris Saint-Germain,Mauricio Pochettino,30000000

In [32]:
df_copy.dtypes

Player Name        object
Chances Created     int64
Assists             int64
Goals               int64
Club               object
Manager            object
Annual Salary       int64
dtype: object

In [36]:
df_copy['Goal conversion rate'] = (df_copy['Goals']/ df_copy['Chances Created']) * 100
df_copy.head()

,Player Name,Chances Created,Assists,Goals,Club,Manager,Annual Salary,Goal conversion rate
0,Cristiano Ronaldo,85,20,35,Manchester United,Ole Gunnar Solskjær,35000000,41.176471
1,Lionel Messi,90,25,30,Paris Saint-Germain,Mauricio Pochettino,40000000,33.333333
2,Robert Lewandowski,70,15,40,Bayern Munich,Julian Nagelsmann,25000000,57.142857
3,Erling Haaland,60,10,35,Borussia Dortmund,Marco Rose,20000000,58.333333
4,Kylian Mbappé,80,18,25,Paris Saint-Germain,Mauricio Pochettino,30000000,31.250000

In [39]:
df_copy['Goal conversion rate'] = df_copy['Goal conversion rate'].round(2)
df_copy.head()

,Player Name,Chances Created,Assists,Goals,Club,Manager,Annual Salary,Goal conversion rate
0,Cristiano Ronaldo,85,20,35,Manchester United,Ole Gunnar Solskjær,35000000,41.18
1,Lionel Messi,90,25,30,Paris Saint-Germain,Mauricio Pochettino,40000000,33.33
2,Robert Lewandowski,70,15,40,Bayern Munich,Julian Nagelsmann,25000000,57.14
3,Erling Haaland,60,10,35,Borussia Dortmund,Marco Rose,20000000,58.33
4,Kylian Mbappé,80,18,25,Paris Saint-Germain,Mauricio Pochettino,30000000,31.25

In [46]:
highest_goal_conversion = df_copy['Goal conversion rate'].idxmax()
player = df_copy.loc[highest_goal_conversion, 'Player Name']
conversion = df_copy.loc[highest_goal_conversion, 'Goal conversion rate']
print(f'The player with highest goal conversion rate is {player} amd his conversion rate is {conversion}')

The player with highest goal conversion rate is Erling Haaland amd his conversion rate is 58.33

In [48]:
df_copy.set_index(['Player Name', 'Club'], inplace = True)
df_copy.head()

,,Chances Created,Assists,Goals,Manager,Annual Salary,Goal conversion rate
Player Name,Club,,,,,,
Cristiano Ronaldo,Manchester United,85,20,35,Ole Gunnar Solskjær,35000000,41.18
Lionel Messi,Paris Saint-Germain,90,25,30,Mauricio Pochettino,40000000,33.33
Robert Lewandowski,Bayern Munich,70,15,40,Julian Nagelsmann,25000000,57.14
Erling Haaland,Borussia Dortmund,60,10,35,Marco Rose,20000000,58.33
Kylian Mbappé,Paris Saint-Germain,80,18,25,Mauricio Pochettino,30000000,31.25

In [49]:
Lukaku_salary = df_copy.loc[('Romelu Lukaku', 'Chelsea'), 'Annual Salary']
print(f'Annual salary of romelu lukaku is {Lukaku_salary}')

Annual salary of romelu lukaku is 27000000

In [52]:
df3 = df_copy.unstack(level = ['Player Name', 'Club'])
df3.head()

                 Player Name         Club
Chances Created  Cristiano Ronaldo   Manchester United      85
                 Lionel Messi        Paris Saint-Germain    90
                 Robert Lewandowski  Bayern Munich          70
                 Erling Haaland      Borussia Dortmund      60
                 Kylian Mbappé       Paris Saint-Germain    80
dtype: object

In [56]:
df3.sort_index(inplace = True)
df3

                      Player Name         Club
Annual Salary         Antoine Griezmann   Barcelona                         24000000
                      Cristiano Ronaldo   Manchester United                 35000000
                      Erling Haaland      Borussia Dortmund                 20000000
                      Harry Kane          Tottenham Hotspur                 32000000
                      Karim Benzema       Real Madrid                       28000000
                      Kylian Mbappé       Paris Saint-Germain               30000000
                      Lionel Messi        Paris Saint-Germain               40000000
                      Mohamed Salah       Liverpool                         30000000
                      Robert Lewandowski  Bayern Munich                     25000000
                      Romelu Lukaku       Chelsea                           27000000
Assists               Antoine Griezmann   Barcelona                               12
                      Cristiano Ronaldo   Manchester United                       20
                      Erling Haaland      Borussia Dortmund                       10
                      Harry Kane          Tottenham Hotspur                       20
                      Karim Benzema       Real Madrid                             15
                      Kylian Mbappé       Paris Saint-Germain                     18
                      Lionel Messi        Paris Saint-Germain                     25
                      Mohamed Salah       Liverpool                               22
                      Robert Lewandowski  Bayern Munich                           15
                      Romelu Lukaku       Chelsea                                 15
Chances Created       Antoine Griezmann   Barcelona                               55
                      Cristiano Ronaldo   Manchester United                       85
                      Erling Haaland      Borussia Dortmund                       60
                      Harry Kane          Tottenham Hotspur                       65
                      Karim Benzema       Real Madrid                             75
                      Kylian Mbappé       Paris Saint-Germain                     80
                      Lionel Messi        Paris Saint-Germain                     90
                      Mohamed Salah       Liverpool                               80
                      Robert Lewandowski  Bayern Munich                           70
                      Romelu Lukaku       Chelsea                                 70
Goal conversion rate  Antoine Griezmann   Barcelona                            32.73
                      Cristiano Ronaldo   Manchester United                    41.18
                      Erling Haaland      Borussia Dortmund                    58.33
                      Harry Kane          Tottenham Hotspur                    46.15
                      Karim Benzema       Real Madrid                          26.67
                      Kylian Mbappé       Paris Saint-Germain                  31.25
                      Lionel Messi        Paris Saint-Germain                  33.33
                      Mohamed Salah       Liverpool                            31.25
                      Robert Lewandowski  Bayern Munich                        57.14
                      Romelu Lukaku       Chelsea                               40.0
Goals                 Antoine Griezmann   Barcelona                               18
                      Cristiano Ronaldo   Manchester United                       35
                      Erling Haaland      Borussia Dortmund                       35
                      Harry Kane          Tottenham Hotspur                       30
                      Karim Benzema       Real Madrid                             20
                      Kylian Mbappé       Paris Saint-Germain                     25
                      Lionel Messi        Paris Saint-Germain                     30
                      Mohamed Salah       Liverpool                               25
                      Robert Lewandowski  Bayern Munich                           40
                      Romelu Lukaku       Chelsea                                 28
Manager               Antoine Griezmann   Barcelona                    Ronald Koeman
                      Cristiano Ronaldo   Manchester United      Ole Gunnar Solskjær
                      Erling Haaland      Borussia Dortmund               Marco Rose
                      Harry Kane          Tottenham Hotspur      Nuno Espírito Santo
                      Karim Benzema       Real Madrid                Carlo Ancelotti
                      Kylian Mbappé       Paris Saint-Germain    Mauricio Pochettino
                      Lionel Messi        Paris Saint-Germain    Mauricio Pochettino
                      Mohamed Salah       Liverpool                     Jürgen Klopp
                      Robert Lewandowski  Bayern Munich            Julian Nagelsmann
                      Romelu Lukaku       Chelsea                      Thomas Tuchel
dtype: object

In [57]:
df3.loc[('Chances Created', 'Karim Benzema')][0]

C:\Users\Windows 11\AppData\Local\Temp\ipykernel_5816\3806278426.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df3.loc[('Chances Created', 'Karim Benzema')][0]

75

In [62]:
messi = df3.loc[('Annual Salary', 'Lionel Messi')][0]
mbappe = df3.loc[('Annual Salary', 'Kylian Mbappé')][0]
combined = messi + mbappe
print(combined)

70000000

C:\Users\Windows 11\AppData\Local\Temp\ipykernel_5816\121333444.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  messi = df3.loc[('Annual Salary', 'Lionel Messi')][0]
C:\Users\Windows 11\AppData\Local\Temp\ipykernel_5816\121333444.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mbappe = df3.loc[('Annual Salary', 'Kylian Mbappé')][0]